// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_p1mdpvfOiOSJnzFBZ-_hjJ6HIGuZ7oQ',
    appId: '1:147529863669:web:40da5c5b4dea0ebef510bc',
    messagingSenderId: '147529863669',
    projectId: 'workouttracker2026kiki',
    authDomain: 'workouttracker2026kiki.firebaseapp.com',
    storageBucket: 'workouttracker2026kiki.firebasestorage.app',
    measurementId: 'G-GZP0GMQXTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnBmd42ajx4h4NgwTXJWb0zFZIx5iWQ4',
    appId: '1:147529863669:android:879ef493e21e06c8f510bc',
    messagingSenderId: '147529863669',
    projectId: 'workouttracker2026kiki',
    storageBucket: 'workouttracker2026kiki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkv1Rvx-UPcPHDAMuY3EDLJ0qciAdPz9A',
    appId: '1:147529863669:ios:de8471fe09dbe852f510bc',
    messagingSenderId: '147529863669',
    projectId: 'workouttracker2026kiki',
    storageBucket: 'workouttracker2026kiki.firebasestorage.app',
    iosBundleId: 'com.sklee.workoutTracker2026',
  );
}
